### ISSUE TITLE
note: This error originates from a subprocess, and is likely not a problem with pip.   ERROR: Failed building wheel for pex

### ISSUE THREAD

**Issue by off-the-az** [EntySec/RomBuster#10]
**Describe the bug**
While installing repository to computer using Python 3.12. During installation I take error: note: This _**error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pex**_

I will be pleasure if u will help me to fix this error!

**Screenshots**
![image](https://github.com/EntySec/RomBuster/assets/96266521/be490033-26f6-44d7-92c2-ec3f47819309)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python Version: 3.12

**Comment by enty8080** [comment]
Windows is not supported.
