### ISSUE TITLE
Didn't got it

### ISSUE THREAD

**Issue by jaykali** [EntySec/RomBuster#3]
Didn't get what happened. Does the attack successful?
![gitissue](https://user-images.githubusercontent.com/62602243/124715387-9663c300-df20-11eb-8d3d-e2a08295a7a9.png)

**Comment by enty8080** [comment]
@jaykali No, attack failed. My fail, I'll add message for it :)

**Comment by hamidhacker021** [comment]
why is allways show none:none
its incorrect!
bug? 
![Capture](https://user-images.githubusercontent.com/52880633/201758478-b5c830a8-55be-418f-a8db-bde53cc7355c.PNG)
