### ISSUE TITLE
None:None

### ISSUE THREAD

**Issue by Hzone-glitch** [EntySec/RomBuster#4]
hey there
why is allways show none:none
its incorrect!
bug?
![Capture](https://user-images.githubusercontent.com/52880633/201898643-71ac42d4-f604-444d-9164-5a765ad98f8d.PNG)

**Comment by enty8080** [comment]
@Hzone-glitch This is not a bug. Somehow program identified empty credentials data on your device which is, as you mentioned, incorrect.
