### ISSUE TITLE
Issue: {router} is not vulnerable

### ISSUE THREAD

**Issue by Zaim-Abbasi** [EntySec/RomBuster#8]
Is there any way to fix the error "is not vulnerable". Maybe by fixing the code or something else. And where to modify the code( I'd figure it out someway myself, if you can't). And it also is saying "Failed to authorize API key".

**Comment by enty8080** [comment]
@Zaim-Abbasi Why would you need to modify the part of code that states that router is not vulnerable. If program says that router is bot vulnerable, this means that router is not vulnerable.

Regarding Shodan, the error with API occurs because of that Shodan stopped supporting free API keys.
