### ISSUE TITLE
Having trouble getting started ;( N00b Issue

### ISSUE THREAD

**Issue by cityji** [EntySec/RomBuster#9]
**Hi,**
i running on ubantu on windows11 through wsl (installed as app in microsoft store) its working as legit
i am already using all my cli tools there like ytdlp,nvim etc. 

I am trying to use this too, as a noob, 
seems i made some mistake from my side? 

but i just followed the instruction from docs, and installation seems successful,
**Please guide me if i made some sort of mistake?**
here's my console output : 

 pip3 install git+https://github.com/EntySec/RomBuster
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/EntySec/RomBuster
  Cloning https://github.com/EntySec/RomBuster to /tmp/pip-req-build-_o178i7z
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/RomBuster /tmp/pip-req-build-_o178i7z
  Resolved https://github.com/EntySec/RomBuster to commit 2dc0712c3f8b9e23993e13661fdc528f776c5911
  Preparing metadata (setup.py) ... done
Collecting badges@ git+https://github.com/EntySec/Badges
  Cloning https://github.com/EntySec/Badges to /tmp/pip-install-sefk6gsv/badges_8280578d338b4d6b956f149807970e28
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/Badges /tmp/pip-install-sefk6gsv/badges_8280578d338b4d6b956f149807970e28
  Resolved https://github.com/EntySec/Badges to commit 5ac3ed226c233c018ea262eb34a8143fc4439185
  Preparing metadata (setup.py) ... done
Collecting pex@ git+https://github.com/EntySec/Pex
  Cloning https://github.com/EntySec/Pex to /tmp/pip-install-sefk6gsv/pex_81368c959c194992883e3ffe39c13188
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/Pex /tmp/pip-install-sefk6gsv/pex_81368c959c194992883e3ffe39c13188
  Resolved https://github.com/EntySec/Pex to commit 50a156daf00a6cb2e99c2c4d06a0a7c9ba844221
  Preparing metadata (setup.py) ... done
Requirement already satisfied: shodan in ./.local/lib/python3.10/site-packages (from rombuster==1.0.0) (1.30.0)
Collecting colorscript@ git+https://github.com/EntySec/ColorScript
  Cloning https://github.com/EntySec/ColorScript to /tmp/pip-install-sefk6gsv/colorscript_7dc9c12ca65546349e3dc70a80679678
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/ColorScript /tmp/pip-install-sefk6gsv/colorscript_7dc9c12ca65546349e3dc70a80679678
  Resolved https://github.com/EntySec/ColorScript to commit 3b86bd4f11035b760559fde4e247cd2a97b58069
  Preparing metadata (setup.py) ... done
Requirement already satisfied: translate in ./.local/lib/python3.10/site-packages (from badges@ git+https://github.com/EntySec/Badges->rombuster==1.0.0) (3.6.1)
Collecting hatasm@ git+https://github.com/EntySec/HatAsm
  Cloning https://github.com/EntySec/HatAsm to /tmp/pip-install-sefk6gsv/hatasm_ce163f57f99f4cbbb72d6f7b3b229265
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/HatAsm /tmp/pip-install-sefk6gsv/hatasm_ce163f57f99f4cbbb72d6f7b3b229265
  Resolved https://github.com/EntySec/HatAsm to commit a9756eca28201536660c6fa28480dbf82b8ebedc
  Preparing metadata (setup.py) ... done
Requirement already satisfied: adb-shell in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.4.4)
Requirement already satisfied: alive_progress in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.1.4)
Requirement already satisfied: manuf in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (1.1.5)
Requirement already satisfied: netaddr in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.9.0)
Requirement already satisfied: netifaces in /usr/lib/python3/dist-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.11.0)
Requirement already satisfied: paramiko in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.3.1)
Requirement already satisfied: pydantic in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.4.1)
Requirement already satisfied: pyelftools in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.30)
Requirement already satisfied: pysnmp in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (4.4.12)
Requirement already satisfied: requests in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.31.0)
Requirement already satisfied: scapy in ./.local/lib/python3.10/site-packages (from pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.5.0)
Requirement already satisfied: click in ./.local/lib/python3.10/site-packages (from shodan->rombuster==1.0.0) (8.1.7)
Requirement already satisfied: XlsxWriter in ./.local/lib/python3.10/site-packages (from shodan->rombuster==1.0.0) (3.1.5)
Requirement already satisfied: click-plugins in ./.local/lib/python3.10/site-packages (from shodan->rombuster==1.0.0) (1.1.1)
Requirement already satisfied: tldextract in ./.local/lib/python3.10/site-packages (from shodan->rombuster==1.0.0) (3.6.0)
Requirement already satisfied: colorama in ./.local/lib/python3.10/site-packages (from shodan->rombuster==1.0.0) (0.4.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.10/site-packages (from requests->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.10/site-packages (from requests->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.10/site-packages (from requests->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.0.5)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.4.8)
Requirement already satisfied: pyasn1 in ./.local/lib/python3.10/site-packages (from adb-shell->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.5.0)
Requirement already satisfied: rsa in ./.local/lib/python3.10/site-packages (from adb-shell->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (4.9)
Requirement already satisfied: grapheme==0.6.0 in ./.local/lib/python3.10/site-packages (from alive_progress->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.6.0)
Requirement already satisfied: about-time==4.2.1 in ./.local/lib/python3.10/site-packages (from alive_progress->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (4.2.1)
Requirement already satisfied: capstone in ./.local/lib/python3.10/site-packages (from hatasm@ git+https://github.com/EntySec/HatAsm->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (5.0.1)
Requirement already satisfied: keystone-engine in ./.local/lib/python3.10/site-packages (from hatasm@ git+https://github.com/EntySec/HatAsm->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.9.2)
Requirement already satisfied: pynacl>=1.5 in ./.local/lib/python3.10/site-packages (from paramiko->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (1.5.0)
Requirement already satisfied: bcrypt>=3.2 in ./.local/lib/python3.10/site-packages (from paramiko->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (4.0.1)
Requirement already satisfied: pydantic-core==2.10.1 in ./.local/lib/python3.10/site-packages (from pydantic->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.10.1)
Requirement already satisfied: annotated-types>=0.4.0 in ./.local/lib/python3.10/site-packages (from pydantic->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.5.0)
Requirement already satisfied: typing-extensions>=4.6.1 in ./.local/lib/python3.10/site-packages (from pydantic->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (4.8.0)
Requirement already satisfied: pysmi in ./.local/lib/python3.10/site-packages (from pysnmp->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (0.3.4)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from pysnmp->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.11.0)
Requirement already satisfied: filelock>=3.0.8 in ./.local/lib/python3.10/site-packages (from tldextract->shodan->rombuster==1.0.0) (3.12.4)
Requirement already satisfied: requests-file>=1.4 in ./.local/lib/python3.10/site-packages (from tldextract->shodan->rombuster==1.0.0) (1.5.1)
Requirement already satisfied: libretranslatepy==2.1.1 in ./.local/lib/python3.10/site-packages (from translate->badges@ git+https://github.com/EntySec/Badges->rombuster==1.0.0) (2.1.1)
Requirement already satisfied: lxml in ./.local/lib/python3.10/site-packages (from translate->badges@ git+https://github.com/EntySec/Badges->rombuster==1.0.0) (4.9.3)
Requirement already satisfied: cffi>=1.4.1 in ./.local/lib/python3.10/site-packages (from pynacl>=1.5->paramiko->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (1.15.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from requests-file>=1.4->tldextract->shodan->rombuster==1.0.0) (1.16.0)
Requirement already satisfied: ply in ./.local/lib/python3.10/site-packages (from pysmi->pysnmp->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (3.11)
Requirement already satisfied: pycparser in ./.local/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.5->paramiko->pex@ git+https://github.com/EntySec/Pex->rombuster==1.0.0) (2.21)
noob@companion:~$ rombuster -a 192.168.1.1
rombuster: command not found
noob@companion:~$ rombuster
rombuster: command not found
noob@companion:~$ rombuster --shodan PSKINdQe1GyxGgecYz2191H2JoS9qvgD
rombuster: command not found
noob@companion:~$

**Comment by enty8080** [comment]
@cityji This problem can be solved easily. Check if `pip3` installs `rombuster` to `PATH`. If not, search for a path where `rombuster` is installed and add it to the `PATH`. Alternatively, you can execute installation command as root.
